// Worker entry (wrangler.toml `main`). Puts the free Workers Cache API in front
// of the OpenNext worker so repeat page views never load the Next.js server.
// All logic lives in src/lib/edge-cache.ts; this file only wires the runtime.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- must pass both before and after a build
// @ts-ignore -- generated by `opennextjs-cloudflare build` (absent in a clean checkout)
import openNextWorker from './.open-next/worker.js';
import {
  cacheVersionFallback,
  createVersionSource,
  fetchDataVersion,
  handleWithEdgeCache,
  renderFailureTracker,
  type EdgeCacheStore,
} from './src/lib/edge-cache';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- must pass both before and after a build
// @ts-ignore -- generated by `opennextjs-cloudflare build` (absent in a clean checkout)
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';

interface Env {
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  /** wrangler.toml [version_metadata]; changes on every deploy. */
  CF_VERSION_METADATA: { id: string };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

let getVersion: (() => Promise<string | null>) | null = null;

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const cache = (caches as unknown as { default: EdgeCacheStore }).default;
    getVersion ??= createVersionSource(
      () => fetchDataVersion(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY),
      cacheVersionFallback(cache)
    );
    // OpenNext exposes this ctx to the app via getCloudflareContext(); queries.ts
    // flags failed reads on it so a degraded render is never cached.
    const tracker = renderFailureTracker(ctx);
    return handleWithEdgeCache(request, {
      cache,
      buildId: env.CF_VERSION_METADATA.id,
      getVersion,
      origin: (req) => openNextWorker.fetch(req, env, tracker.ctx),
      waitUntil: (promise) => ctx.waitUntil(promise),
      renderFailed: tracker.failed,
    });
  },
};

export default worker;
