/**
 * Regenerates src/lib/countries.ts from the `country-state-city` package.
 *
 * Server code must not import `country-state-city`: the package is ~8.7 MB of
 * JS (every city on Earth), and pulling it into the Worker bundle made every
 * cold request exceed the free-plan CPU limit. Server-side validation only
 * needs country names + ISO codes, so we snapshot those here.
 *
 *   npx tsx scripts/gen-countries.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Country } from 'country-state-city';

const rows = Country.getAllCountries().map((c) => `  ['${c.isoCode}', ${JSON.stringify(c.name)}],`);

const out = `// GENERATED by scripts/gen-countries.ts from country-state-city — do not edit.
// A server-safe snapshot of [ISO 3166-1 alpha-2, display name] pairs. See the
// generator for why server code must not import country-state-city directly.
export const COUNTRIES: ReadonlyArray<readonly [isoCode: string, name: string]> = [
${rows.join('\n')}
];
`;

writeFileSync(join(__dirname, '..', 'src', 'lib', 'countries.ts'), out);
console.log(`Wrote ${rows.length} countries`);
